#define T_LPAREN                          1
#define T_RPAREN                          2
#define T_LBRACE                          3
#define T_RBRACE                          4
#define T_LBRACK                          5
#define T_RBRACK                          6
#define T_LAND                            7
#define T_LOR                             8
#define T_BAND                            9
#define T_BOR                            10
#define T_BXOR                           11
#define T_EQ                             12
#define T_NE                             13
#define T_GT                             14
#define T_GE                             15
#define T_LT                             16
#define T_LE                             17
#define T_MATCH                          18
#define T_QUESTION                       19
#define T_ADD                            20
#define T_SUB                            21
#define T_MUL                            22
#define T_DIV                            23
#define T_MOD                            24
#define T_EXP                            25
#define T_LNOT                           26
#define T_BNOT                           27
#define T_COMMA                          28
#define T_SEMI                           29
#define T_INT                            30
#define T_LONG                           31
#define T_FLOAT                          32
#define T_DOUBLE                         33
#define T_IDENT                          34
