#define T_LPAREN                          1
#define T_RPAREN                          2
#define T_LBRACE                          3
#define T_RBRACE                          4
#define T_LBRACK                          5
#define T_RBRACK                          6
#define T_LNOT                            7
#define T_BNOT                            8
#define T_LAND                            9
#define T_LOR                            10
#define T_BAND                           11
#define T_BOR                            12
#define T_BXOR                           13
#define T_EQ                             14
#define T_NE                             15
#define T_GT                             16
#define T_GE                             17
#define T_LT                             18
#define T_LE                             19
#define T_MATCH                          20
#define T_ADD                            21
#define T_SUB                            22
#define T_MUL                            23
#define T_DIV                            24
#define T_MOD                            25
#define T_EXP                            26
#define T_IDENT                          27
#define T_IN                             28
#define T_DOT                            29
#define T_COMMA                          30
#define T_BOOL                           31
#define T_INT                            32
#define T_LONG                           33
#define T_FLOAT                          34
#define T_DOUBLE                         35
